
---
apiVersion: v1
kind: Namespace
metadata: 
  name: minio-ns
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: minio-cm
  namespace: minio-ns
data:
  MINIO_ROOT_USER: root
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-hsvc.minio-ns.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-sk
  namespace: minio-ns
type: Opaque
data:
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
spec: 
  clusterIP: None
  selector:
    app: minio
    name: minio-pod
  ports:
  - name: data
    port: 9000 
    targetPort: 9000  
  - name: console
    port: 9090 
    targetPort: 9090  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
spec:
  replicas: 4
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-pod
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: minio
        name: minio-pod
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: minio-container
        image: bitnami/minio:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-sk
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - name: data
          containerPort: 9000
        - name: console
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /data
        resources: 
          requests:
            cpu: 200m
            memory: 250Mi
          limits: 
            cpu: 200m
            memory: 250Mi

---

apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-pod
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio-ns
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"         
    nginx.ingress.kubernetes.io/limit-burst: "20"       
    nginx.ingress.kubernetes.io/limit-connections: "5"  
spec:
  ingressClassName: nginx
  rules:
  - host: data.157.230.196.33.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
  
  - host: console.157.230.196.33.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9090


