volumes:
  data-vol:

networks:
  mynet:
    driver: bridge

services:
  #docker run -d --name=mydb --network=mynet -v data-vol:/var/lib/mysql stackupiss/northwind-db:v1
  mydb:
    image: stackupiss/northwind-db:v1
    build:
      context: database
    #specify docker file
    # dockerfile
    volumes:
    - data-vol:/var/lib/mysql
    networks:
    - mynet

  # docker run -d -p 8080:3000 --name myapp --network=mynet -e DB_HOST=mydb -e DB_USER=root -e DB_PASSWORD=changeit  stackupiss/northwind-app:v1
  myapp:
    image: stackupiss/northwind-app:v1
    build:
      context: server
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - mynet
    ports:
    - 8080:3000
    depends_on: 
    - mydb